execute pathogen#infect()

set nocompatible
syntax enable
set background=light
let g:solarized_termcolors=16
"let g:solarized_termtrans=1
colorscheme solarized

set tabstop=2
set shiftwidth=2
set expandtab

filetype plugin indent on

set nobackup
set nowritebackup
set directory=$HOME/.vim/tmp//,.

set relativenumber
set numberwidth=5
set laststatus=2

set ignorecase
set smartcase

set incsearch
set hlsearch

set clipboard=unnamed "yank to clipboard

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" FORGET ABOUT ARROW KEYS 
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
map <Left> <Nop>
map <Right> <Nop>
map <Up> <Nop>
map <Down> <Nop>

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" POWERLINE SETTINGS
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:Powerline_symbols = 'fancy'

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Switching between numbers and relative numbers 
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
autocmd InsertEnter * :set number
autocmd InsertLeave * :set relativenumber
