# Colors
autoload -U colors
colors
setopt prompt_subst

local smiley="%(?,%{$fg[green]%}☺%{$reset_color%},%{$fg[red]%}☹%{$reset_color%})"

PROMPT='
%~
${smiley}  %{$reset_color%}'

RPROMPT='%{$fg[white]%} $(~/.rvm/bin/rvm-prompt)$(~/bin/git-cwd-info)%{$reset_color%}'

setopt menucomplete
autoload compinit
compinit

PATH=$PATH:$HOME/.rvm/bin:/usr/local/sbin 

alias vimrc="vim $HOME/.vimrc"
