# Colors
autoload -U colors
colors
setopt prompt_subst

local smiley="%(?,%{$fg[green]%}☺%{$reset_color%},%{$fg[red]%}☹%{$reset_color%})"

PROMPT='
%~
${smiley}  %{$reset_color%}'

RPROMPT='%{$fg[white]%} $(~/.bin/git-cwd-info)%{$reset_color%}'

setopt menucomplete
autoload compinit
compinit
export EDITOR="vim"

# Aliases

alias r="bundle exec rails"
alias z="bundle exec zeus"
alias g="git"
alias rk="bundle exec rake"
alias be="bundle exec"

alias ccat="pygmentize -g"
alias ls="ls -G"
alias l="ls -laG"
alias ru="rvm use"
alias vimrc="vim $HOME/.vimrc"
alias zshrc="vim $HOME/.zshrc"
alias szs="source $HOME/.zshrc"

alias ssup="sis server start -d -P"
alias ssdown="sis server stop -d"

alias gco="git checkout"
alias gst="git status"
alias gcm="git commit -am"
alias gpl="git pull"
alias gps="git push"
alias gdiff="git diff --color"

alias cap="bundle exec cap"

[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator
export NLS_KEY_PWD=test

stty -ixon -ixoff


export GOPATH=$HOME/.gocode
export PATH=$GOPATH/bin:$PATH
# tmuxifier
export PATH="$HOME/bin:$HOME/.tmuxifier/bin:/usr/local/bin:$PATH"
eval "$(tmuxifier init -)"
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

eval "$(direnv hook zsh)"


BASE16_SCHEME="tomorrow"
BASE16_SHELL="$HOME/.config/base16-shell/base16-$BASE16_SCHEME.dark.sh"
[[ -s $BASE16_SHELL ]] && . $BASE16_SHELL
